version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: diabetes_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: diabetes_ai
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - diabetes_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: diabetes_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - diabetes_network

  minio:
    image: minio/minio:latest
    container_name: diabetes_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - diabetes_network

  redis:
    image: redis:7.2-alpine
    container_name: diabetes_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - diabetes_network

volumes:
  mongodb_data:
    driver: local
  qdrant_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  diabetes_network:
    driver: bridge 